version: "3.8"

services:
  db:
    container_name: ${PG_HOST}
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_PORT: ${PG_HOST}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: pg_isready -U ${PG_USER} -d ${PG_DATABASE}
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    ports:
      - ${PG_PORT}:5432
    networks:
      - test_network

  tests:
    image: python:3.11  # Образ для тестов
    container_name: test_runner
    working_dir: /app/backend  # Рабочая директория внутри контейнера
    volumes:
      - .:/app  # Монтируем весь проект в контейнер
    networks:
      - test_network
    depends_on:
      db:
        condition: service_healthy
    environment:
      PYTHONPATH: /app/backend  # Устанавливаем PYTHONPATH для тестов
    command: >
      /bin/bash -c "
      cp /app/.env /app/backend/.env &&
      pip install pipenv &&
      cd /app/backend &&
      pipenv install --dev &&
      pipenv run pytest -v -s
      "

networks:
  test_network:
    name: test_network
